ShopCenter/ShopCenter/urls.py
from django.contrib import admin
from django.urls import path,include
from WebCenter import views




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("WebCenter.urls")),
    path('services/', include("services.urls")),
    path('blog/', include("blog.urls")),
    path('contact/', include("contact.urls")),
    path('shop/', include("shop.urls")),
    path('car/', include("marketcar.urls")),
    path("authentication/",include("authentication.urls")),
    path("delivery/",include("delivery.urls")),


]

ShopCenter/blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [

    path('', views.Blog,name="blog"),
    path("category/<int:category_id>/", views.category ,name="category"),
]

#urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ShopCenter/marketcar/urls.py
from django.urls import path
from . import views

app_name="car"

urlpatterns=[
    path("add/<int:product_id>",views.add_product,name="add"),
    path("delete/<int:product_id>",views.delete_product,name="delete"),
    path("quit/<int:product_id>",views.quit_product,name="quit"),
    path("clean/<int:product_id>",views.clean_product,name="clean"),
]

ShopCenter/shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [

    path('', views.Shop,name="shop"),

]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ShopCenter/shop/models.py
from django.db import models


class CatProd(models.Model):
    name=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name="catprod"
        verbose_name_plural="categoria_Productos"
    def __str__(self):
        return self.name
    



class Product(models.Model):
    name=models.CharField(max_length=50)
    cat=models.ForeignKey(CatProd,on_delete=models.CASCADE)
    image=models.ImageField(upload_to="shop",null=True,blank=True)
    price=models.FloatField()
    availability=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name="product"
        verbose_name_plural="products"
    def __str__(self):
        return self.name

ShopCenter/shop/views.py
from django.shortcuts import render
from .models import Product,CatProd

# Create your views here.

def Shop(request):
    products=Product.objects.all()
    return render(request,"shop/shop.html",{"products":products})

ShopCenter/shop/templates/car/widget.html
<table class="table table-bordered" style="color:white;">

    <thead>
        <tr>
            <th colspan="3" class="text-center">
                Shopping cart
                
            </th>
        </tr>
        <tr>
            <th> Products</th>
            <th> Quantity </th>
            <th> Total </th>
        </tr>
    </thead>
    <tbody>
        {% if request.session.car.items %}
            {% for key,value in request.session.car.items %}
            <tr class="text-center">


                <td>{{ value.name }}</td>
                <td>{{ value.quantity }}</td>
                <td>
                    <a href="{% url 'car:add' value.product_id %}" class="btn btn-sm btn-success">+</a>
                    <a href=" {% url 'car:quit' value.product_id %}" class="btn btn-sm btn-success">-</a> <br>
                    {{value.price}} USD
                </td>

            </tr>
            {% endfor%}
        {% else %}
        <tr>
            <td colspan="3">
                <div class="alert alert-danger text-center">
                    No Products
                </div>
            </td>
        </tr>
        {% endif %} 
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                Total: {{total_cart_amount}} USD
            </td>
        </tr>

        {% if request.session.car.items %}
        <tr>
            <td colspan="3" style="text-align:center">
                <a href="#" class="btn btn-success"> Request </a>
            </td>
        </tr>
        {% endif %}
    </tfoot>
</table>